# Generated by Django 3.0.3 on 2020-03-18 21:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('orders_completed', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='truck_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('number_of_active_orders', models.IntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('incomplete_orders', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trucks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField(default=0)),
                ('available_capacity', models.PositiveIntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucker.driver')),
                ('truck_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucker.truck_company')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='truck_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucker.truck_company'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
