# Generated by Django 3.0.4 on 2020-04-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_company',
            name='docs_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
