# Generated by Django 3.0.3 on 2020-03-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_company',
            name='company_name',
        ),
    ]
