# Generated by Django 3.0.4 on 2020-04-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck_company',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
