# Generated by Django 3.0.4 on 2020-04-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucker', '0002_auto_20200411_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_company',
            name='is_approved',
        ),
    ]
