# Generated by Django 3.0.3 on 2020-03-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucker', '0002_remove_truck_company_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='password',
        ),
        migrations.RemoveField(
            model_name='truck_company',
            name='username',
        ),
    ]
