# Generated by Django 3.0.4 on 2020-04-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucker', '0003_remove_truck_company_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trucks',
            name='model',
        ),
    ]
