# Generated by Django 3.0.4 on 2020-04-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0014_merge_20200418_1341'),
        ('trucker', '0004_remove_trucks_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='counter_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_accepted', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipper.order')),
            ],
        ),
    ]
