# Generated by Django 3.0.4 on 2020-04-19 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucker', '0005_counter_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter_offer',
            name='trucker_user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='trucker.truck_company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counter_offer',
            name='is_accepted',
            field=models.BooleanField(default=None),
        ),
    ]
