# Generated by Django 3.0.4 on 2020-04-19 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucker', '0007_auto_20200419_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter_offer',
            name='status',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
