# Generated by Django 3.0.4 on 2020-05-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='order_email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
