# Generated by Django 3.0.3 on 2020-03-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(default='EB SA de SV', max_length=30),
            preserve_default=False,
        ),
    ]
