# Generated by Django 3.0.4 on 2020-05-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20200501_1310'),
        ('authorization', '0003_auto_20200503_2153'),
    ]

    operations = [
    ]
