# Generated by Django 3.0.4 on 2020-05-05 23:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_merge_20200504_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_type',
            field=models.CharField(choices=[('PF', 'Persona Física'), ('PM', 'Persona Moral')], default='PF', max_length=15, verbose_name='Corporation Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(max_length=30, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(max_length=30, verbose_name='User Type'),
        ),
    ]
