# Generated by Django 3.0.4 on 2020-05-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20200505_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_type',
            field=models.CharField(max_length=15, verbose_name='Corporation Type'),
        ),
    ]
