# Generated by Django 3.0.3 on 2020-03-18 21:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shipper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('company_name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=50)),
                ('active_orders', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('delivery_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('delivery_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('pickup_date', models.DateField(default=datetime.date.today)),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('distance', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('carta_porte', models.ImageField(blank=True, null=True, upload_to=shipper.models.order.get_carta_porte_path)),
                ('orden_de_embarco', models.ImageField(blank=True, null=True, upload_to=shipper.models.order.get_orden_de_embarco)),
                ('shipment_number', models.PositiveIntegerField(default=0)),
                ('numero_de_pedido', models.PositiveIntegerField(default=0)),
                ('numero_de_abaran', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trucker.driver')),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipper.shipper')),
                ('truck_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trucker.truck_company')),
            ],
        ),
    ]
