# Generated by Django 3.0.4 on 2020-03-25 07:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shipper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_orders', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('delivery_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('delivery_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('pickup_date', models.DateField(default=datetime.date.today)),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('distance', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('carta_porte', models.ImageField(blank=True, null=True, upload_to=shipper.models.order.get_carta_porte_path)),
                ('orden_de_embarco', models.ImageField(blank=True, null=True, upload_to=shipper.models.order.get_orden_de_embarco)),
                ('shipment_number', models.PositiveIntegerField(default=0)),
                ('numero_de_pedido', models.PositiveIntegerField(default=0)),
                ('numero_de_abaran', models.PositiveIntegerField(default=0)),
                ('pickup_time', models.TimeField(default=django.utils.timezone.now)),
                ('delivery_time', models.TimeField(default=django.utils.timezone.now)),
                ('contents', models.TextField(default='')),
                ('instructions', models.TextField(default='')),
                ('truck_type', models.CharField(choices=[('Low Boy', 'Low Boy'), ('Caja Seca 48 pies', 'Caja Seca 48 pies'), ('Refrigerado 48 pies', 'Refrigerado 48 pies'), ('Plataforma 48 pies', 'Plataforma 48 pies'), ('Caja Seca 53 pies', 'Caja Seca 53 pies'), ('Refrigerado 53 pies', 'Refrigerado 53 pies'), ('Plataforma 53 pies', 'Plataforma 53 pies'), ('Full', 'Full'), ('Plataforma Full', 'Plataforma Full'), ('Torton Caja Seca', 'Torton Caja Seca'), ('Torton Refrigerado', 'Torton Refrigerado'), ('Troton Plataforma', 'Troton Plataforma'), ('Rabon Caja Seca', 'Rabon Caja Seca'), ('Rabon Refrigerado', 'Rabon Refrigerado'), ('Rabon Plataforma', 'Rabon Plataforma'), ('Camioneta 5.5 tons', 'Camioneta 5.5 tons'), ('Camioneta 3.5 tons', 'Camioneta 3.5 tons'), ('Camioneta 3.5 tons Plataforma', 'Camioneta 3.5 tons Plataforma'), ('Camioneta 1.5 tons', 'Camioneta 1.5 tons'), ('Camioneta 3.5 tons Redilla', 'Camioneta 3.5 tons Redilla')], default='LB', max_length=40)),
                ('status', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trucker.driver')),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipper.shipper')),
                ('truck_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trucker.truck_company')),
            ],
        ),
    ]
