# Generated by Django 3.0.4 on 2020-05-08 03:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('customer_order_no', models.CharField(default='', max_length=50)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('delivery_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('delivery_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('pickup_address', models.TextField(default='')),
                ('delivery_address', models.TextField(default='')),
                ('pickup_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Pickup Date')),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price')),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Weight')),
                ('carta_porte', models.FileField(blank=True, null=True, upload_to='')),
                ('orden_de_embarco', models.FileField(blank=True, null=True, upload_to='')),
                ('shipment_number', models.PositiveIntegerField(default=0)),
                ('numero_de_pedido', models.PositiveIntegerField(default=0)),
                ('numero_de_abaran', models.PositiveIntegerField(default=0)),
                ('pickup_time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Pickup Time')),
                ('delivery_time', models.TimeField(default=django.utils.timezone.now)),
                ('contents', models.CharField(default='', max_length=255, verbose_name='Contents')),
                ('instructions', models.TextField(default='', verbose_name='Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('truck_type', models.CharField(choices=[('Low Boy', 'Low Boy'), ('Caja Seca 48 pies', 'Caja Seca 48 pies'), ('Refrigerado 48 pies', 'Refrigerado 48 pies'), ('Plataforma 48 pies', 'Plataforma 48 pies'), ('Caja Seca 53 pies', 'Caja Seca 53 pies'), ('Refrigerado 53 pies', 'Refrigerado 53 pies'), ('Plataforma 53 pies', 'Plataforma 53 pies'), ('Full Caja Seca', 'Full Caja Seca'), ('Full Refrigerado', 'Full Refrigerado'), ('Full Plataforma', 'Full Plataforma'), ('Torton Caja Seca', 'Torton Caja Seca'), ('Torton Refrigerado', 'Torton Refrigerado'), ('Torton Plataforma', 'Torton Plataforma'), ('Rabon Caja Seca', 'Rabon Caja Seca'), ('Rabon Refrigerado', 'Rabon Refrigerado'), ('Rabon Plataforma', 'Rabon Plataforma'), ('Camioneta 5.5 tons Seca', 'Camioneta 5.5 tons Seca'), ('Camioneta 5.5 tons Refrigerada', 'Camioneta 5.5 tons Refrigerada'), ('Camioneta 5.5 tons Plataforma', 'Camioneta 5.5 tons Plataforma'), ('Camioneta 3.5 tons Seca', 'Camioneta 3.5 tons Seca'), ('Camioneta 3.5 tons Refrigerada', 'Camioneta 3.5 tons Refrigerada'), ('Camioneta 3.5 tons Redila', 'Camioneta 3.5 tons Redila'), ('Camioneta 1.5 tons Seca', 'Camioneta 1.5 tons Seca'), ('Camioneta 1.5 tons Refrigerada', 'Camioneta 1.5 tons Refrigerada'), ('Camioneta 1.5 tons Redila', 'Camioneta 1.5 tons Redila')], default='LB', max_length=40, verbose_name='Truck Type')),
                ('status', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='order_post_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_orders', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRecurringOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shipper.order')),
                ('weekdays', models.CharField(default='0000000', max_length=40)),
                ('number_of_weeks', models.CharField(default='# weeks', max_length=40)),
                ('end_opt', models.CharField(default='option0', max_length=40)),
                ('start_day', models.CharField(default='start', max_length=40)),
                ('end_by_day', models.CharField(default='end', max_length=40)),
                ('indefinite', models.BooleanField(default=False)),
                ('occurrences', models.CharField(default='occs', max_length=40)),
            ],
            bases=('shipper.order',),
        ),
        migrations.CreateModel(
            name='status_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('new_status', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('date_time_changed', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.order')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.shipper')),
            ],
        ),
    ]
