# Generated by Django 3.0.4 on 2020-03-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
    ]
