<<<<<<< HEAD:src/shipper/migrations/0002_auto_20200424_1404.py
# Generated by Django 3.0.4 on 2020-04-24 21:04
=======
# Generated by Django 2.2.5 on 2020-04-25 02:20
>>>>>>> b93435806338d183838288645e4b4b97b0d6d2ab:src/shipper/migrations/0002_auto_20200424_2120.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucker', '0001_initial'),
<<<<<<< HEAD:src/shipper/migrations/0002_auto_20200424_1404.py
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> b93435806338d183838288645e4b4b97b0d6d2ab:src/shipper/migrations/0002_auto_20200424_2120.py
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_update',
            name='trucker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucker.truck_company'),
        ),
        migrations.AddField(
            model_name='shipper',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_post_notification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.order'),
        ),
        migrations.AddField(
            model_name='order_post_notification',
            name='truckers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trucker.driver'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipper.shipper'),
        ),
        migrations.AddField(
            model_name='order',
            name='truck_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trucker.truck_company'),
        ),
    ]
