# Generated by Django 3.0.3 on 2020-03-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0002_remove_shipper_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='password',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='username',
        ),
    ]
