# Generated by Django 3.0.3 on 2020-03-20 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0003_auto_20200319_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contents',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='truck_type',
            field=models.CharField(choices=[('Low Boy', 'Low Boy'), ('Caja Seca 48 pies', 'Caja Seca 48 pies'), ('Refrigerado 48 pies', 'Refrigerado 48 pies'), ('Plataforma 48 pies', 'Plataforma 48 pies'), ('Caja Seca 53 pies', 'Caja Seca 53 pies'), ('Refrigerado 53 pies', 'Refrigerado 53 pies'), ('Plataforma 53 pies', 'Plataforma 53 pies'), ('Full', 'Full'), ('Plataforma Full', 'Plataforma Full'), ('Torton Caja Seca', 'Torton Caja Seca'), ('Torton Refrigerado', 'Torton Refrigerado'), ('Troton Plataforma', 'Troton Plataforma'), ('Rabon Caja Seca', 'Rabon Caja Seca'), ('Rabon Refrigerado', 'Rabon Refrigerado'), ('Rabon Plataforma', 'Rabon Plataforma'), ('Camioneta 5.5 tons', 'Camioneta 5.5 tons'), ('Camioneta 3.5 tons', 'Camioneta 3.5 tons'), ('Camioneta 3.5 tons Plataforma', 'Camioneta 3.5 tons Plataforma'), ('Camioneta 1.5 tons', 'Camioneta 1.5 tons'), ('Camioneta 3.5 tons Redilla', 'Camioneta 3.5 tons Redilla')], default='LB', max_length=40),
        ),
    ]
