# Generated by Django 3.0.4 on 2020-05-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0003_auto_20200501_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contents',
            field=models.CharField(default='', max_length=255, verbose_name='Contents'),
        ),
    ]
