# Generated by Django 3.0.4 on 2020-05-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0004_auto_20200501_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carta_porte',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='orden_de_embarco',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
