# Generated by Django 3.0.4 on 2020-04-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0005_auto_20200327_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
