# Generated by Django 3.0.4 on 2020-04-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucker', '0001_initial'),
        ('shipper', '0006_auto_20200402_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='trucker_connections',
            field=models.ManyToManyField(to='trucker.truck_company'),
        ),
    ]
