# Generated by Django 3.0.4 on 2020-04-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0006_auto_20200402_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipper',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
