# Generated by Django 3.0.4 on 2020-04-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0008_auto_20200411_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='trucker_connections',
        ),
        migrations.DeleteModel(
            name='Connection_Request',
        ),
    ]
