# Generated by Django 3.0.4 on 2020-04-13 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0008_remove_shipper_is_approved'),
        ('shipper', '0009_auto_20200411_1527'),
    ]

    operations = [
    ]
