# Generated by Django 3.0.4 on 2020-04-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0010_merge_20200412_2305'),
        ('shipper', '0010_merge_20200412_1710'),
    ]

    operations = [
    ]
