# Generated by Django 3.0.4 on 2020-04-17 22:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucker', '0003_remove_truck_company_is_approved'),
        ('shipper', '0011_merge_20200412_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('new_status', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('date_time_changed', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.order')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.shipper')),
                ('trucker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucker.truck_company')),
            ],
        ),
    ]
