# Generated by Django 3.0.4 on 2020-04-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0011_merge_20200412_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='truck_type',
            field=models.CharField(choices=[('Low Boy', 'Low Boy'), ('Caja Seca 48 pies', 'Caja Seca 48 pies'), ('Refrigerado 48 pies', 'Refrigerado 48 pies'), ('Plataforma 48 pies', 'Plataforma 48 pies'), ('Caja Seca 53 pies', 'Caja Seca 53 pies'), ('Refrigerado 53 pies', 'Refrigerado 53 pies'), ('Plataforma 53 pies', 'Plataforma 53 pies'), ('Full Caja Seca', 'Full Caja Seca'), ('Full Refrigerado', 'Full Refrigerado'), ('Full Plataforma', 'Full Plataforma'), ('Torton Caja Seca', 'Torton Caja Seca'), ('Torton Refrigerado', 'Torton Refrigerado'), ('Torton Plataforma', 'Torton Plataforma'), ('Rabon Caja Seca', 'Rabon Caja Seca'), ('Rabon Refrigerado', 'Rabon Refrigerado'), ('Rabon Plataforma', 'Rabon Plataforma'), ('Camioneta 5.5 tons Seca', 'Camioneta 5.5 tons Seca'), ('Camioneta 5.5 tons Refrigerada', 'Camioneta 5.5 tons Refrigerada'), ('Camioneta 5.5 tons Plataforma', 'Camioneta 5.5 tons Plataforma'), ('Camioneta 3.5 tons Seca', 'Camioneta 3.5 tons Seca'), ('Camioneta 3.5 tons Refrigerada', 'Camioneta 3.5 tons Refrigerada'), ('Camioneta 3.5 tons Redila', 'Camioneta 3.5 tons Redila'), ('Camioneta 1.5 tons Seca', 'Camioneta 1.5 tons Seca'), ('Camioneta 1.5 tons Refrigerada', 'Camioneta 1.5 tons Refrigerada'), ('Camioneta 1.5 tons Redila', 'Camioneta 1.5 tons Redila')], default='LB', max_length=40),
        ),
    ]
