# Generated by Django 3.0.4 on 2020-04-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0012_auto_20200414_1819'),
        ('shipper', '0013_order_post_notification'),
    ]

    operations = [
    ]
